image: gabrieletassoni/vscode-devcontainers-thecore:3
variables:
  GITLAB_EMAIL: gabriele.tassoni@gmail.com
  GITLAB_USER_NAME: Gabriele Tassoni
  GITLAB_OAUTH_TARGET: https://oauth2:${GITLAB_PAT}@${GITLAB_HOST}/${CI_PROJECT_PATH}
  GITLAB_GEM_REPO_TARGET: https://${GEM_HOST}/
  GEM_HOST_API_KEY: ${GEMS_REPO_CREDENTIALS}
stages:
  - build
  - release
build_gem:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  stage: build
  script:
    - /usr/bin/gem-compile.sh
